# Generated by Django 4.0.4 on 2022-05-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('time', models.TimeField()),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
