# Generated by Django 4.0.4 on 2022-06-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoticPetCareTrackerapi', '0002_foodtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='fruit',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='foodtype',
            old_name='green',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='meat',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='vegetable',
        ),
        migrations.RemoveField(
            model_name='foodtype',
            name='weed',
        ),
    ]
